### ISSUE TITLE
bokstavsorning på posterna

### ISSUE THREAD

**Issue by AntonLilja** [datasektionen/skywhale#1]
När man väljer ut posterna för ett nytt val hade det varit nice om de legat i bokstavsordning. Vilken ordning är det för poster under valsidan? Om det inte är bokstavsordning eller smart ordning (typ D-rek först och resten bokstavsordning etc) så blir det rätt svårt hitta

**Comment by karlek** [comment]
Skulle det inte vara bättre ifall vi har en pragmatisk sortering istället (D-REK poster; fanbärare och vice fanbärare; KÖD och SS ligger jämsides?)
