### ISSUE TITLE
Flera val, nominera till fel

### ISSUE THREAD

**Issue by AntonLilja** [datasektionen/skywhale#12]
Om man har flera val så går det att nominera folk till alla poster och sedan välja val. Därmed går det att nominera någon till en post som det inte är val till på det SM. SM kommer sällan så normal fall är det nog inte ett problem men med extra SM och stuff blir det problem.

**Comment by jonasdahl** [comment]
Frontend-problem egentligen. Om man nominerar "fel" poster till ett SM kommer de bara skippas. Men ska fixas, om nån vecka.
