### ISSUE TITLE
Förlängning av nominerings/acceptansstop

### ISSUE THREAD

**Issue by AntonLilja** [datasektionen/skywhale#13]
En specefik post kan få sitt nominerings/acceptansstop förlängt enligt stadgarna. Det gäller desutom olika regler för fyllnadsval och vanligt val (som ibland infaller under samma SM). Det borde därför vara möjligt att ändra just nominering och acceptansstop för varje specifik post.

**Comment by jonasdahl** [comment]
Ska titta på det här efter min tenta nästa vecka!
