### ISSUE TITLE
RSS-feed - se ångringsriktning

### ISSUE THREAD

**Issue by Fexlom** [datasektionen/skywhale#17]
Det skulle vara informativt att skriva till RSS-feeden i vilken "riktning" en ångring gjorts, d.v.s. om någon ångrat ett ja-svar eller ett nej-svar. Som det är nu måste man titta på kontexten kring den nomineringen för att bli varse.

**Comment by Fexlom** [comment]
@jonasdahl är detta fixat eller är det något som inte kommer att fixas?

**Comment by jonasdahl** [comment]
Kommer inte fixas inom en rimlig framtid, iaf inte av mig
