### ISSUE TITLE
Blacklist

### ISSUE THREAD

**Issue by AntonLilja** [datasektionen/skywhale#18]
Folk håller på med att nominera lärare vilket är fett onice. Vore jävligt bra om vi kunde lägga exportera alla dem och lägga i ett filter (blacklist) och en möjlighet att addera mailadresser till filtret när man redigerar personer

**Comment by jonasdahl** [comment]
Hmm, har tänkt på det här. Det bästa sättet kanske är att låta valberedningen manuellt få "whitelista" folk, innan ett mejl går ut. När man whitelistar skulle ett mejl gå ut automatiskt. Annars är ju skadan redan skedd när man blacklistar (i och för sig hindrar det ju framtida spam). Vad tycker du @AntonLilja?

**Comment by AntonLilja** [comment]
En whitelist hade också funkat, tappar lite speed i systemet men det får sektionen ta
