### ISSUE TITLE
varning om att det skickas över osäker anslutning (firefox)

### ISSUE THREAD

**Issue by AntonLilja** [datasektionen/skywhale#2]
Ansluter man till https://skywhale.datasektionen.se/ med firefox så varnar den för osäker anslutning på allt man gör som kräver att man skickar data. Den verkar som standard skicka över http

**Comment by jonasdahl** [comment]
Gäller det här också https://val.datasektionen.se?

**Comment by AntonLilja** [comment]
Ja, måste vara någonstans i koden där det hårdkodat står http. Firefox varnar om du är inne på en sida med https men någon del använder http (för då blir man ju "lurad" av sidan)
