### ISSUE TITLE
Behåll radbrytningar i beskrivningar

### ISSUE THREAD

**Issue by Plongy** [datasektionen/skywhale#20]
Systemet vaskar radbrytningar i postbeskrivningar, det är ganska trist när man har lite längre texter som man vill ha radbrytningar i.

En lösning skulle vara om man kunde stoppa in `<br>` (som systemet inte escapear).

**Comment by jonasdahl** [comment]
Vaar? Man kan väl inte beskriva poster i skywhale?

**Comment by jonasdahl** [comment]
Men jag kör en new line -> <br /> på valbeskrivningen

**Comment by Plongy** [comment]
Sry, tänkte på postbeskrivningarna som hämtas från dfunkt och visas på sidan över ens nomineringar.
