### ISSUE TITLE
Obekräftade personer syns som nominerade

### ISSUE THREAD

**Issue by MrLarssonJr** [datasektionen/skywhale#22]
En person ny person för systemet syns som nominerade innan valberedningen bekräftat att personen är en sektionsmedlem. Det  kanske är tänkt beteende?

**Comment by jonasdahl** [comment]
Jag tror att det mest tänktes för att förhindra att oönskade personer fick mejl, och jag tror det är bra för användarvänlighetens skull att det syns direkt när man nominerar någon. Men det kan givetvis ändras om ni vill, ska jag göra det? Själv tycker jag det är en nice feature att det är som det är.

**Comment by MrLarssonJr** [comment]
Jag tror du har rätt. Det är bättre från ett användarvänlighets perspektiv. Och så länge ingen blir folk som inte har med sektionen spammas och en icke datalog blir vald så är det ok.  Hade bara fått för mig att de dök upp efter kontrollen.

Tack för snabbt svar 😄
