### ISSUE TITLE
Kan ej nominera

### ISSUE THREAD

**Issue by MrLarssonJr** [datasektionen/skywhale#28]
Får 503 
<img width="952" alt="screen shot 2018-04-24 at 13 55 12" src="https://user-images.githubusercontent.com/4522613/39185331-21c4a026-47c7-11e8-9fe0-d930ba283e35.png">

**Comment by MrLarssonJr** [comment]
Verkar vara problem med att nominera nya personer, dvs. personer som ej är vitlistade.

Att nominera mig eller Victor S. fungerar

**Comment by jonasdahl** [comment]
Borde vara fixat nu, var fel i env-variabel

**Comment by MrLarssonJr** [comment]
Tack grymt för snabb fix! <3
