### ISSUE TITLE
503 server error when blacklisting mail

### ISSUE THREAD

**Issue by MrLarssonJr** [datasektionen/skywhale#29]
<img width="924" alt="screen shot 2018-05-06 at 14 28 37" src="https://user-images.githubusercontent.com/4522613/39673297-bf3100a4-5139-11e8-8849-407e5f124c79.png">

Försökte blacklista jeslundq@kth.se genom admingränssnittet och fick ovan fel.

<img width="952" alt="screen shot 2018-05-06 at 14 29 55" src="https://user-images.githubusercontent.com/4522613/39673302-f031a33e-5139-11e8-97f6-4045d5eb0be4.png">

**Comment by jonasdahl** [comment]
Undersökte problemet och det verkar redan finnas en jeslundq i blacklisten, så det försöker skapas en duplicate i databasen och då går det sönder. Fixar när jag har tid.

**Comment by MrLarssonJr** [comment]
Aha! Tänkte inte på att undersöka det!

Schysst! 😊

6 maj 2018 kl. 18:55 skrev Jonas Dahl <notifications@github.com<mailto:notifications@github.com>>:


Undersökte problemet och det verkar redan finnas en jeslundq i blacklisten, så det försöker skapas en duplicate i databasen och då går det sönder. Fixar när jag har tid.
