### ISSUE TITLE
zfinger på nomineringsidan

### ISSUE THREAD

**Issue by AntonLilja** [datasektionen/skywhale#6]
Att de ska fylla i kth-mail är nice för det brukade vi vara tvugna att leta upp. zfinger är bästa verktyget för det, vore sjukt nice om den integrerades med en sökruta på nomineringsidan. Enklara lösning är att ha en länk på sidan till zfinger (många typ 1an har ingen aning att zfinger existerar) så typ "Kan du inte allas kthmail utantill? Kolla zfinger"

**Comment by jonasdahl** [comment]
Det här är redan implementerat, men man måste vänta en stund innan listan kommer upp, ska göra det tydligare med en loading-gif
