### ISSUE TITLE
uppdatera årskurs på folk som loggat in

### ISSUE THREAD

**Issue by AntonLilja** [datasektionen/skywhale#8]
De som loggat in får ingen årskurs även om någon skriver in den, årskurs är typ nice att skriva på folk. Vore nice om de också blev uppdaterade

**Comment by jonasdahl** [comment]
Apropå årskurser: det borde finnas i Z-finger en vacker dag och då borde det inte behövas. Men fixar det här så länge :)

**Comment by jonasdahl** [comment]
Det här borde vara fixat
